inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - 'passenger_datadog.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

# Offense count: 2
# Configuration parameters: Exclude.
Naming/FileName:
  Exclude:
    - 'bin/passenger-datadog'

Style/Documentation:
  Enabled: false
